id: IE64B7488
default_language: en
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:28:13.741057
last_modified: 2023-01-04 11:28:13.741064
source_metadata:
  collections:
  - Alak Zenkar Rinpoche
  - Works of Tibetan Masters
bases:
  ED9F:
    title: Biography of Shechen Gyaltsab Gyurme Pema Namgyal
    base_file: ED9F.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
